### ISSUE TITLE
typo: std::lock_guard<std::mutex> guar(mutex);

### ISSUE THREAD

**Issue by allanhaywood** [wichtounet/articles#10]
On line 41 of articles/src/threads/part2/SafeGuard.cpp

Should this: 
std::lock_guard<std::mutex> guar(mutex);

be this:
std::lock_guard<std::mutex> guard(mutex);

Changing guar to guard

**Comment by wichtounet** [comment]
Thank you very much. 

This is fixed in 7c5b74c734c28bbe75ec0a391c25d16cb7e5e67b
