### ISSUE TITLE
minor update to condition_variable example

### ISSUE THREAD

**Issue by azadkuh** [wichtounet/articles#11]
it seems to be too late, but would you please update your sample code and blog text about `condition_variable`:

https://github.com/wichtounet/articles/blob/e93d57a64587815034690038ac45f15221552f5a/src/threads/part3/condition_variables.cpp#L44
https://github.com/wichtounet/articles/blob/e93d57a64587815034690038ac45f15221552f5a/src/threads/part3/condition_variables.cpp#L56

the problem:
it's better to unlock the `std::unique_lock<>` before calling `notify_one();`:
```cpp
l.unlock();
not_empty.notify_one();
```

> Manual unlocking is done before notifying, to avoid waking up the waiting thread only to block again (see notify_one for details)

[cppreference](http://en.cppreference.com/w/cpp/thread/condition_variable)

**Comment by wichtounet** [comment]
Hi, 

Thanks for this. I didn't know this at the time I wrote the article. 

It's indeed slightly better to do it before. 

I'll try to update the blog and the code when I got some time. I'll keep open the issue until I do the changes. 

Baptiste

**Comment by wichtounet** [comment]
This is fixed now :)

Thanks again :)
