### ISSUE TITLE
Copy-past mistake

### ISSUE THREAD

**Issue by dmitofclubs** [wichtounet/articles#12]
In [src/fold_expressions.cpp](https://github.com/wichtounet/articles/blob/master/src/fold_expressions.cpp):
```
...
template<typename T1, typename... T>
auto old_mul(T1 s, T... ts){
    return s + old_sum(ts...);;
}
...
```

should be
```
...
auto old_mul(T1 s, T... ts){
  return s * old_mul(ts...);
}
...
```

**Comment by wichtounet** [comment]
Very good catch, thanks :)

Next time if you know the fix, you can directly open a pull request, you will be credited as a contributor and Github makes this very easy!
