### ISSUE TITLE
build fails, 

### ISSUE THREAD

**Issue by borissmidt** [wichtounet/articles#7]
whenever i try to build i get the follwing error:
ld: unrecognized option '-DNDEBUG' *
*and all other options passed to it i tried. 
Im using  linux and tried gcc and clang to build it but nothing seems to work .

**Comment by wichtounet** [comment]
Hi, 

the variable $LD must point to a valid compiler, not a linker (probably not good idea, sorry). 

try:

```
export CXX=g++
export LD=g++
make
```

Tell me if there are any more issues after that. 

Baptiste

**Comment by borissmidt** [comment]
Well that did the trick.
