### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by songzhuoran** [wichtounet/articles#9]
-e \x1b[31;01m[release]\x1b[0m Compile \x1b[35;01msrc/threads/part1/Hello0.cpp\x1b[0m
-e \x1b[31;01m[release]\x1b[0m Link \x1b[35;01mrelease/bin/threads_p1_hello0\x1b[0m
ld: unrecognised emulation mode: arch=native
Supported emulations: elf_x86_64 elf32_x86_64 elf_i386 elf_iamcu i386linux elf_l1om elf_k1om i386pep i386pe
Makefile:38: recipe for target 'release/bin/threads_p1_hello0' failed
make: *** [release/bin/threads_p1_hello0] Error 1

**Comment by wichtounet** [comment]
Hello, 

Sorry for the delay, I was in holidays. 

This should now be fixed, sorry for the inconvenience.

Baptiste
